server:
    port: 8081

#eureka  config
eureka:
    instance:
         hostname: localhost
    client:
         registerWithEureka: false
         fetchRegistry: false
         serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
